#pragma checksum "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5a486a338eb401e3022ef180b9b500d6c17fdecb"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Index.cshtml", typeof(AspNetCore.Views_Home_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\_ViewImports.cshtml"
using CarRental;

#line default
#line hidden
#line 2 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\_ViewImports.cshtml"
using CarRental.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5a486a338eb401e3022ef180b9b500d6c17fdecb", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"529c8bd122fb22e8a9a1a9692f07307d414d2a18", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
  
    ViewData["Title"] = "Index";

#line default
#line hidden
            BeginContext(43, 1919, true);
            WriteLiteral(@"
<div ng-app=""CarRental"">
    <div ng-view></div>
</div>

<script src=""https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"" type=""text/javascript""></script>
<script src=""https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular-route.min.js"" type=""text/javascript""></script>
<script type=""text/javascript"">
    angular
        .module('CarRental', ['ngRoute'])
        .config(function ($routeProvider) {
            $routeProvider                            //Routing//
                .when('/',
                {
                    templateUrl: 'pages/index.html',
                    controller: 'IndexController'
                })
                .when('/clients',
                {
                    templateUrl: 'pages/clients.html',
                    controller: 'ClientsController'
                })
                .when('/cars',
                {
                    templateUrl: 'pages/cars.html',
                    controller: 'CarsController'
           ");
            WriteLiteral(@"     })
                .when('/addCar',
                {
                    templateUrl: 'pages/addEditCar.html',
                    controller: 'AddCarController'
                })
                .when('/editCar/:carId',
                {
                    templateUrl: 'pages/addEditCar.html',
                    controller: 'EditCarController'
                })
                .otherwise({
                    redirectTo: '/'
                });
        })
        //Setting the modules that will be used for the controllers and functions for the logic of the controllers //
        .controller('IndexController', ['$scope', '$http', function ($scope, $http) {
            $scope.message = 'Car Rental';
        }])
        .controller('ClientsController', ['$scope', '$http', function ($scope, $http) {
            $scope.clients = [];
            $http.get('");
            EndContext();
            BeginContext(1963, 35, false);
#line 52 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                  Write(Url.Action("GetClients", "Clients"));

#line default
#line hidden
            EndContext();
            BeginContext(1998, 316, true);
            WriteLiteral(@"')
                .then(function (response) {          //Get request for the method//
                    $scope.clients = response.data;
                });
        }])
        .controller('CarsController', ['$scope', '$http', function ($scope, $http) {
            $scope.cars = [];
            $http.get('");
            EndContext();
            BeginContext(2315, 29, false);
#line 59 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                  Write(Url.Action("GetCars", "Cars"));

#line default
#line hidden
            EndContext();
            BeginContext(2344, 238, true);
            WriteLiteral("\')\r\n                .then(function (response) {          //Get request for the method//\r\n                    $scope.cars = response.data;\r\n                });\r\n\r\n            $scope.Delete = function (car) {\r\n                $http.delete(\"");
            EndContext();
            BeginContext(2583, 29, false);
#line 65 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                         Write(Url.Action("GetCars", "Cars"));

#line default
#line hidden
            EndContext();
            BeginContext(2612, 536, true);
            WriteLiteral(@"/"" + car.id).then(function (response){
                    var index = $scope.cars.indexOf(car);
                    $scope.cars.splice(index, 1);
                });
            }
        }])
        .controller('AddCarController', ['$scope', '$http', '$location', function ($scope, $http, $location) {
            $scope.car =
            {
                id : 0,
                type : '',
                name : ''

            };

            $scope.SaveCar = function()
            {
                $http.post('");
            EndContext();
            BeginContext(3149, 29, false);
#line 82 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                       Write(Url.Action("PostCar", "Cars"));

#line default
#line hidden
            EndContext();
            BeginContext(3178, 476, true);
            WriteLiteral(@"', $scope.car)
                    .then(function (response) {
                        $location.path('/cars');
                    })
            }

        }])
        .controller('EditCarController', ['$scope', '$http', '$location', '$routeParams', function ($scope, $http, $location, $routeParams) {
            $scope.car =
            {
                id : 0,
                type : '',
                name : ''

            };

            $http.get('");
            EndContext();
            BeginContext(3655, 29, false);
#line 98 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                  Write(Url.Action("GetCars", "Cars"));

#line default
#line hidden
            EndContext();
            BeginContext(3684, 236, true);
            WriteLiteral("/\' + $routeParams.carId)\r\n                .then(function (response) {          \r\n                    $scope.car = response.data;\r\n                });\r\n\r\n            $scope.SaveCar = function()\r\n            {\r\n                $http.put(\'");
            EndContext();
            BeginContext(3921, 29, false);
#line 105 "D:\WADEngpaslednesh\WAD.WebApplication.7922\CarRental.7922\CarRental\Views\Home\Index.cshtml"
                      Write(Url.Action("GetCars", "Cars"));

#line default
#line hidden
            EndContext();
            BeginContext(3950, 212, true);
            WriteLiteral("/\' + $routeParams.carId, $scope.car)\r\n                    .then(function (response) {\r\n                        $location.path(\'/cars\');\r\n                    });\r\n            }\r\n\r\n        }]);\r\n\r\n\r\n</script>\r\n\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
