#pragma checksum "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e5f9d05d088bbfa8f10a725e243b657801695850"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Index.cshtml", typeof(AspNetCore.Views_Home_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\_ViewImports.cshtml"
using CarRental;

#line default
#line hidden
#line 2 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\_ViewImports.cshtml"
using CarRental.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e5f9d05d088bbfa8f10a725e243b657801695850", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"529c8bd122fb22e8a9a1a9692f07307d414d2a18", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\Home\Index.cshtml"
  
    ViewData["Title"] = "Index";

#line default
#line hidden
            BeginContext(43, 949, true);
            WriteLiteral(@"
<h2>Car List</h2>

<div id=""carsContainer"" ng-app=""carsApp"">
    <div ng-controller=""carsController"">
        <table class=""table"">
            <tbody>
                <tr ng-repeat=""car in cars"">
                    <td> {{car.id}} </td>
                    <td> {{car.type}} </td>
                    <td> {{car.name}} </td>
                    <td> <input type=""button"" value=""x"" class=""btn-danger"" ng-click=""delete(car)"" />
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td> <input ng-model=""type"" placeholder=""Type"" type=""text"" /> </td>
                    <td><input ng-model=""name"" placeholder=""Name"" type=""text"" /></td>
                    <td><input class=""btn-primary"" value=""+"" type=""button"" ng-click=""add()"" /></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

");
            EndContext();
            DefineSection("Scripts", async() => {
                BeginContext(1010, 271, true);
                WriteLiteral(@"

    <script src=""https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"" type=""text/javascript""></script>
    <script>
        angular.module('carsApp', [])
        .controller('carsController', function ($scope, $http) {
                $http.get(""");
                EndContext();
                BeginContext(1282, 29, false);
#line 38 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\Home\Index.cshtml"
                      Write(Url.Action("GetCars", "Cars"));

#line default
#line hidden
                EndContext();
                BeginContext(1311, 307, true);
                WriteLiteral(@""").then(function (response) {
                    $scope.cars = response.data; });
                $scope.add = function () {
                    var car = {
                        type: $scope.type,
                        name: $scope.name
                    };

                    $http.post(""");
                EndContext();
                BeginContext(1619, 29, false);
#line 46 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\Home\Index.cshtml"
                           Write(Url.Action("PostCar", "Cars"));

#line default
#line hidden
                EndContext();
                BeginContext(1648, 302, true);
                WriteLiteral(@""", car).then(function (response) {
                        $scope.cars.push(response.data);
                    });

                    $scope.type = '';
                    $scope.name = '';
                }
                $scope.delete = function (car) {
                    $http.delete(""");
                EndContext();
                BeginContext(1951, 29, false);
#line 54 "C:\Users\SKH\Desktop\WAD PORTFOLIO\CarRental\CarRental\Views\Home\Index.cshtml"
                             Write(Url.Action("PostCar", "Cars"));

#line default
#line hidden
                EndContext();
                BeginContext(1980, 235, true);
                WriteLiteral("/\" + car.id).then(function (response) {\r\n                        var index = $scope.cars.indexOf(car);\r\n                        $scope.cars.splice(index, 1);\r\n                    });\r\n                }\r\n            });\r\n    </script>\r\n");
                EndContext();
            }
            );
            BeginContext(2218, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
